### ISSUE TITLE
How to install Metatogger on a different Disk

### ISSUE THREAD

**Issue by random-explorer** [luminescence-software/Metatogger-Support#5]
First, thank you for your amazing app. 
I wish if there is no option in the installer to change the File location of the app. Is this possible?

**Comment by CyberSinh** [comment]
There is an _Options_ button to select the install location in the EXE setup package:

![image](https://github.com/luminescence-software/Metatogger-Support/assets/10407531/ff0f5232-a0bb-41c9-a46b-d6591f637ac6)

![image](https://github.com/luminescence-software/Metatogger-Support/assets/10407531/5253fd25-97bd-4968-9eb3-6a3893cbedd7)

With the MSI setup package, you can use the command line to set the _Install Location_ setting:
`msiexec /i "C:\msi\Metatogger-Installer.msi" INSTALLLOCATION="C:\myfolder" /qb`
